### ISSUE TITLE
Issue installing RDK

### ISSUE THREAD

**Issue by utishrajk** [OSEHRA-Sandbox/eHMP#2] opened 2017-10-26 15:03 UTC
Hi,

I'm following the instructions at http://github.com/OSEHRA-Sandbox/eHMP/wiki/eHMP-Install-Instructions and I'm in Phase 2. When I do `gradle deployRdkDev`, the build is failing. I've attached the logs below. I've already destroyed the machine using `gradle destroyRdk `and tried to run again but getting the same error. Can you please advise?

Thanks,
UR

Parallel execution is an incubating feature.
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
Defining custom 'check' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:production:rdk:deletePreparsedApiDocs UP-TO-DATE
:production:rdk:pruneNpm
:production:rdk:clean UP-TO-DATE
:production:rdk:installFakeOracleDB
:production:rdk:installNpm
:production:rdk:build
:production:rdk:ccowInstallNpm
:production:rdk:writeInstallNpm
:production:rdk:zipRDK UP-TO-DATE
:deployrdkDev
LOG_LEVEL: warn
===========================================================YOOOOOOO===============================
chefArgs : [-o, rdk_provision@2.0.204, --environment, _default, --config, /root/Projects/vistacore/.chef/knife.rb, --force-formatter, -l, warn]
newVars : [DEV_DEPLOY:true, MACHINE_NAME:rdk, DRIVER:vagrant, ACTION:converge, ALLOW_WEB_ACCESS:true, PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin]
Starting Chef Client, version 12.14.89[0m
[2017-10-26T10:56:01-04:00] WARN: Run List override has been provided.
[2017-10-26T10:56:01-04:00] WARN: Original Run List: []
[2017-10-26T10:56:01-04:00] WARN: Overridden Run List: [recipe[rdk_provision@2.0.204]]
resolving cookbooks for run list: ["rdk_provision@2.0.204"][0m
Synchronizing Cookbooks:[0m
  - rdk_provision (2.0.204)[0m
  - machine (2.0.40)[0m
  - rdk (2.0.96)[0m
  - jbpm (2.0.97)[0m
  - common (2.0.12)[0m
  - packages (2.0.9)[0m
  - role_cookbook (2.0.17)[0m
  - logrotate (1.9.1)[0m
  - java_wrapper (2.0.6)[0m
  - nodejs_wrapper (2.0.4)[0m
  - bluepill_wrapper (2.0.5)[0m
  - oracle_wrapper (2.0.16)[0m
  - jboss-eap_wrapper (2.0.6)[0m
  - oracle-xe_wrapper (2.0.11)[0m
  - yum_wrapper (2.0.6)[0m
  - rubygems_wrapper (2.0.5)[0m
  - beats (2.0.3)[0m
  - ntp (1.8.6)[0m
  - timezone-ii (0.2.0)[0m
  - hostnames (0.3.6)[0m
  - sssd_ldap_wrapper (2.0.6)[0m
  - ohai (2.0.6)[0m
  - java (1.32.0)[0m
  - nodejs (2.4.0)[0m
  - bluepill (2.3.1)[0m
  - oracle (1.2.2)[0m
  - jboss-eap (2.1.1)[0m
  - oracle-xe (0.1.0)[0m
  - swap (0.3.8)[0m
  - yum (3.5.4)[0m
  - rubygems (1.0.2)[0m
  - filebeat_wrapper (2.0.3)[0m
  - topbeat_wrapper (2.0.2)[0m
  - hostsfile (2.4.5)[0m
  - sssd_ldap (1.0.2)[0m
  - yum-epel (0.6.0)[0m
  - build-essential (2.2.2)[0m
  - ark (0.9.0)[0m
  - apt (2.7.0)[0m
  - homebrew (1.13.0)[0m
  - rsyslog (1.15.0)[0m
  - filebeat (0.2.8)[0m
  - topbeat (0.1.2)[0m
  - windows (1.37.0)[0m
  - 7-zip (1.0.2)[0m
  - powershell (3.2.3)[0m
  - chef_handler (1.1.9)[0m
  - ms_dotnet (2.6.1)[0m
Installing Cookbook Gems:[0m
Compiling Cookbooks...[0m
[2017-10-26T10:56:06-04:00] WARN: Chef::Provider::YumRepository already exists!  Cannot create deprecation class for LWRP provider yum_repository from cookbook yum
[2017-10-26T10:56:06-04:00] WARN: YumRepository already exists!  Deprecation class overwrites Custom resource yum_repository from cookbook yum
[2017-10-26T10:56:06-04:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2017-10-26T10:56:06-04:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Recipe: rdk_provision::rdk[0m
  * chef_gem[chef-provisioning-ssh] action install (up to date)
  Converging 4 resources[0m
  * chef_gem[chef-provisioning-ssh] action install (up to date)
  * machine_boot[boot rdk machine to the vagrant environment] action vagrant (up to date)
  * vagrant_box[opscode-centos-6.5] action create[2017-10-26T10:56:06-04:00] WARN: Class Chef::Provider::VagrantBox does not declare 'provides :vagrant_box'.
[2017-10-26T10:56:06-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
 (up to date)
  * chef_node[rdk-root-master] action delete
    [32m- delete node rdk-root-master at chefzero://localhost:8889[0m
[0m  * machine[rdk-root-master] action ready[2017-10-26T10:56:07-04:00] WARN: Class Chef::Provider::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2017-10-26T10:56:07-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.

    [32m- create node rdk-root-master at chefzero://localhost:8889[0m
    [32m-   add normal.tags = nil[0m
    [32m-   add normal.chef_provisioning = {"reference"=>{"driver_url"=>"vagrant:/root/Projects/vistacore/.chef/vms", "driver_version"=>"0.11.0", "vm_name"=>"rdk-root-master", "vm_file_path"=>"/root/Projects/vistacore/.chef/vms/rdk-root-master.vm", "allocated_at"=>"2017-10-26 14:56:07 UTC", "host_node"=>"chefzero://localhost:8889/nodes/"}}[0m
    [32m-   update run_list from [] to ["placeholder"][0m
    [32m- update node rdk-root-master at chefzero://localhost:8889[0m
    [32m-   add normal.chef_provisioning.reference.needs_reload = false[0m
    [32m-   update run_list from ["recipe[placeholder]"] to ["placeholder"][0m
[0m  * chef_node[rdk-root-master] action delete (skipped due to only_if)
  * ruby_block[set_ip_attribute_for_rdk] action run
    [32m- execute the ruby block set_ip_attribute_for_rdk[0m
[0m  * machine[rdk-root-master-node] action converge
    [32m- update node rdk-root-master-node at chefzero://localhost:8889[0m
    [32m-   add normal.stack = "root-master"[0m
    [32m-   add normal.allow_ldap_access = nil[0m
    [32m-   add normal.nexus_url = "http://nexus.osehra.org:8081"[0m
    [32m-   add normal.data_bag_string = "k33p1ts@f3"[0m
    [32m-   add normal.dev_deploy = true[0m
    [32m-   add normal.using_vagrant = true[0m
    [32m-   add normal.rdk = {:profile=>nil, :source=>"http://nexus.osehra.org:8081/nexus/content/repositories/releases/us/vistacore/rdk/rdk//rdk-.zip", :version=>nil}[0m
    [32m-   add normal.beats = {:logging=>false}[0m
    [32m-   remove normal.stack[0m
    [32m-   remove normal.allow_ldap_access[0m
    [32m-   remove normal.nexus_url[0m
    [32m-   remove normal.data_bag_string[0m
    [32m-   remove normal.dev_deploy[0m
    [32m-   remove normal.using_vagrant[0m
    [32m-   remove normal.rdk[0m
    [32m-   remove normal.beats[0m
    [32m- update node rdk-root-master-node at chefzero://localhost:8889[0m
    [32m-   add normal.stack = "root-master"[0m
    [32m-   add normal.allow_ldap_access = nil[0m
    [32m-   add normal.nexus_url = "http://nexus.osehra.org:8081"[0m
    [32m-   add normal.data_bag_string = "k33p1ts@f3"[0m
    [32m-   add normal.dev_deploy = true[0m
    [32m-   add normal.using_vagrant = true[0m
    [32m-   add normal.rdk = {:profile=>nil, :source=>"http://nexus.osehra.org:8081/nexus/content/repositories/releases/us/vistacore/rdk/rdk//rdk-.zip", :version=>nil}[0m
    [32m-   add normal.beats = {:logging=>false}[0m
    [32m-   remove normal.stack[0m
    [32m-   remove normal.allow_ldap_access[0m
    [32m-   remove normal.nexus_url[0m
    [32m-   remove normal.data_bag_string[0m
    [32m-   remove normal.dev_deploy[0m
    [32m-   remove normal.using_vagrant[0m
    [32m-   remove normal.rdk[0m
    [32m-   remove normal.beats[0m
    [32m- update node rdk-root-master-node at chefzero://localhost:8889[0m
    [32m-   add normal.stack = "root-master"[0m
    [32m-   add normal.allow_ldap_access = nil[0m
    [32m-   add normal.nexus_url = "http://nexus.osehra.org:8081"[0m
    [32m-   add normal.data_bag_string = "k33p1ts@f3"[0m
    [32m-   add normal.dev_deploy = true[0m
    [32m-   add normal.using_vagrant = true[0m
    [32m-   add normal.rdk = {:profile=>nil, :source=>"http://nexus.osehra.org:8081/nexus/content/repositories/releases/us/vistacore/rdk/rdk//rdk-.zip", :version=>nil}[0m
    [32m-   add normal.beats = {:logging=>false}[0m
    [32m-   remove normal.stack[0m
    [32m-   remove normal.allow_ldap_access[0m
    [32m-   remove normal.nexus_url[0m
    [32m-   remove normal.data_bag_string[0m
    [32m-   remove normal.dev_deploy[0m
    [32m-   remove normal.using_vagrant[0m
    [32m-   remove normal.rdk[0m
    [32m-   remove normal.beats[0m
    [32m- run 'sh -c /etc/chef/install.sh' on rdk-root-master-node[0m
    [32m- update node rdk-root-master-node at chefzero://localhost:8889[0m
    [32m-   add normal.stack = "root-master"[0m
    [32m-   add normal.allow_ldap_access = nil[0m
    [32m-   add normal.nexus_url = "http://nexus.osehra.org:8081"[0m
    [32m-   add normal.data_bag_string = "k33p1ts@f3"[0m
    [32m-   add normal.dev_deploy = true[0m
    [32m-   add normal.using_vagrant = true[0m
    [32m-   add normal.rdk = {:profile=>nil, :source=>"http://nexus.osehra.org:8081/nexus/content/repositories/releases/us/vistacore/rdk/rdk//rdk-.zip", :version=>nil}[0m
    [32m-   add normal.beats = {:logging=>false}[0m
    [32m-   remove normal.stack[0m
    [32m-   remove normal.allow_ldap_access[0m
    [32m-   remove normal.nexus_url[0m
    [32m-   remove normal.data_bag_string[0m
    [32m-   remove normal.dev_deploy[0m
    [32m-   remove normal.using_vagrant[0m
    [32m-   remove normal.rdk[0m
    [32m-   remove normal.beats[0m
    [rdk-root-master-node] /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/node/immutable_collections.rb:79:in `block (2 levels) in <class:ImmutableArray>': Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"' (Chef::Exceptions::ImmutableAttributeModification)
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:150:in `block in visit_Psych_Nodes_Sequence'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:150:in `each'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:150:in `visit_Psych_Nodes_Sequence'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:302:in `block in revive_hash'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `each'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `each_slice'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `revive_hash'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:161:in `visit_Psych_Nodes_Mapping'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:276:in `visit_Psych_Nodes_Document'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych/nodes/node.rb:37:in `to_ruby'
                           	from /opt/chef/embedded/lib/ruby/2.1.0/psych.rb:246:in `load'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/config_file.rb:335:in `load_file'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/config_file.rb:198:in `initialize'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:295:in `new'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:295:in `configuration'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:48:in `<class:GemEnvironment>'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:44:in `<class:Rubygems>'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:43:in `<class:Package>'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:42:in `<class:Provider>'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:41:in `<class:Chef>'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/rubygems.rb:40:in `<top (required)>'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/providers.rb:76:in `<top (required)>'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef.rb:25:in `<top (required)>'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
                           	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-client:23:in `<top (required)>'
                           	from /usr/bin/chef-client:50:in `load'
                           	from /usr/bin/chef-client:50:in `<main>'
    [0m
    ================================================================================[0m
    [31mError executing action `converge` on resource 'machine[rdk-root-master-node]'[0m
    ================================================================================[0m
    
[0m    RuntimeError[0m
    ------------[0m
    Error: command 'chef-client -c /etc/chef/client.rb -l warn' exited with code 1.
[0m    
[0m    Resource Declaration:[0m
    ---------------------[0m
    # In /root/Projects/vistacore/.chef/local-mode-cache/cache/cookbooks/rdk_provision/recipes/rdk.rb
[0m    
[0m     72: machine machine_name do
[0m     73:   driver "ssh"
[0m     74:   converge node[:machine][:converge]
[0m     75:   machine_options lazy {
[0m     76:     {
[0m     77:       :transport_options => {
[0m     78:         :ip_address => node[:machine][:production_settings][machine_ident.to_sym][:ip],
[0m     79:         :username => node[:machine][:production_settings][machine_ident.to_sym][:ssh_username],
[0m     80:         :ssh_options => {
[0m     81:           :keys => [
[0m     82:             node[:machine][:production_settings][machine_ident.to_sym][:ssh_key]
[0m     83:           ],
[0m     84:         },
[0m     85:         :options => {
[0m     86:           :prefix => 'sudo ',
[0m     87:         }
[0m     88:       },
[0m     89:       :convergence_options => node[:machine][:convergence_options]
[0m     90:     }
[0m     91:   }
[0m     92:   attributes(
[0m     93:     stack: node[:machine][:stack],
[0m     94:     allow_ldap_access: node[:machine][:allow_ldap_access],
[0m     95:     nexus_url: node[:common][:nexus_url],
[0m     96:     data_bag_string: node[:common][:data_bag_string],
[0m     97:     dev_deploy: ENV['DEV_DEPLOY'] == "true" ? true : false,
[0m     98:     using_vagrant: node[:machine][:driver] == "vagrant",
[0m     99:     rdk: {
[0m    100:       profile: db_item,
[0m    101:       source: artifact_url(node[:rdk_provision][:artifacts][:rdk]),
[0m    102:       version: ENV['RDK_VERSION']
[0m    103:     },
[0m    104:     beats: {
[0m    105:       logging: node[:machine][:logging]
[0m    106:   }
[0m    107:   )
[0m    108:   files lazy { node[:rdk_provision][:rdk][:copy_files] }
[0m    109:   chef_environment node[:machine][:environment]
[0m    110:   run_list r_list
[0m    111:   action node[:machine][:action]
[0m    112: end
[0m    113: 
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in /root/Projects/vistacore/.chef/local-mode-cache/cache/cookbooks/rdk_provision/recipes/rdk.rb:72:in `from_file'
[0m    
[0m    machine("rdk-root-master-node") do
[0m      action [:converge]
[0m      retries 0
[0m      retry_delay 2
[0m      default_guard_interpreter :default
[0m      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"deploy", :signing_key_filename=>"/root/Projects/vistacore/.chef/deploy.pem", :api_version=>"0"}}
[0m      chef_environment "_default"
[0m      driver "ssh"
[0m      machine_options #<Chef::DelayedEvaluator:0x000000047af9f0@/root/Projects/vistacore/.chef/local-mode-cache/cache/cookbooks/rdk_provision/recipes/rdk.rb:75>
[0m      declared_type :machine
[0m      cookbook_name "rdk_provision"
[0m      recipe_name "rdk"
[0m      attributes {:stack=>"root-master", :allow_ldap_access=>nil, :nexus_url=>"http://nexus.osehra.org:8081", :data_bag_string=>"k33p1ts@f3", :dev_deploy=>true, :using_vagrant=>true, :rdk=>{:profile=>nil, :source=>"http://nexus.osehra.org:8081/nexus/content/repositories/releases/us/vistacore/rdk/rdk//rdk-.zip", :version=>nil}, :beats=>{:logging=>false}, "tags"=>nil, "chef_provisioning"=>{"reference"=>{"driver_url"=>"ssh:/root/Projects/vistacore/.chef/provisioning/ssh", "driver_version"=>"0.1.0", "target_name"=>"rdk-root-master-node", "allocated_at"=>"2017-10-26 14:31:08 UTC", "host"=>"chefzero://localhost:8889/nodes/", "ssh_machine_file"=>"/root/Projects/vistacore/.chef/provisioning/ssh/rdk-root-master-node.json", "updated_at"=>"2017-10-26 14:31:08 UTC"}}}
[0m      files #<Chef::DelayedEvaluator:0x000000047a7bd8@/root/Projects/vistacore/.chef/local-mode-cache/cache/cookbooks/rdk_provision/recipes/rdk.rb:108>
[0m      run_list ["recipe[packages::enable_internal_sources@2.0.9]", "recipe[role_cookbook::vagrant@2.0.17]", "role[resource_server]", "recipe[rdk@2.0.96]"]
[0m    end
[0m    
[0m    Platform:[0m
    ---------[0m
    x86_64-linux[0m
    
[0m[0m
Running handlers:[0m
[2017-10-26T10:56:19-04:00] ERROR: Running exception handlers
Running handlers complete
[0m[2017-10-26T10:56:19-04:00] ERROR: Exception handlers complete
Chef Client failed. 3 resources updated in 24 seconds[0m
[2017-10-26T10:56:19-04:00] FATAL: Stacktrace dumped to /root/Projects/vistacore/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-10-26T10:56:19-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-10-26T10:56:19-04:00] ERROR: machine[rdk-root-master-node] (rdk_provision::rdk line 72) had an error: RuntimeError: Error: command 'chef-client -c /etc/chef/client.rb -l warn' exited with code 1.

[2017-10-26T10:56:19-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
:deployrdkDev FAILED

BUILD FAILED

Total time: 35.01 secs

**Comment by shabiel** [comment] 2017-10-26 15:14
Okay. This error happens when your VM is already running. You need to try
destroy again; if it doesn't work (and apparently it didn't), run vagrant
destroy -f <machine name> in ~/Projects/vistacore/.chef/vms.

--Sam

**Comment by utishrajk** [comment] 2017-10-26 15:46
I destroyed it again using vagrant destroy -f <machine name> and the machine is destroyed. I ran gradle deployRdkDev and I'm getting the same error again. Anything else I can try?

Thanks Sam for the response.

**Comment by shabiel** [comment] 2017-10-27 10:53
Utish,

Do you work for an OSEHRA organizational member? I will provide support to
members.

--Sam

**Comment by utishrajk** [comment] 2017-10-27 14:27
We are working for a federal agency in an open source project trying to utilize eHMP. If you can give us some guidelines, I'll really appreciate that. Thanks.

**Comment by utishrajk** [comment] 2017-10-30 13:50
The project is Consent2Share: https://bhits.github.io/consent2share/index.html

The federal sponsor is SAMHSA: https://www.samhsa.gov/

Thanks.

**Comment by shabiel** [comment] 2018-02-08 16:01
There is now a new version of eHMP. I am closing this issue. Try and see if it fixes your issue.

**Closed by shabiel** 2018-02-08 16:01 UTC

**Comment by jiangsheng** [comment] 2020-05-19 17:30
I am having the same issue on the latest version of eHMP.

**Comment by jiangsheng** [comment] 2020-05-20 17:46
looks like the problem is on chef install
chef-client -version gives the same error.
